# Motor status from motion_controller
std_msgs/Header  header
float32          motor_left_front    # RPM
float32          motor_right_front   # RPM
float32          motor_left_rear     # RPM
float32          motor_right_rear    # RPM
float32          motor_current       # Total current (A)
float32          motor_voltage       # Voltage (V)
float32          temperature         # Motor temperature (C)
