# Execute path following (motion_controller Action Server, called by master_controller)
geometry_msgs/PoseStamped[]  waypoints
float32                      target_velocity    # m/s

---
bool                         success
uint32                       completed_waypoints
float32                      deviation_max      # m

---
uint32                       current_waypoint_idx
float32                      lateral_deviation  # m
float32                      path_progress      # 0.0~1.0
